// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClcguSXqfoAeBDM77DxUxMgBHDkAkOp0o',
    appId: '1:43291649087:web:854837086767f6c446448a',
    messagingSenderId: '43291649087',
    projectId: 'smartcare-fyp',
    authDomain: 'smartcare-fyp.firebaseapp.com',
    storageBucket: 'smartcare-fyp.firebasestorage.app',
    measurementId: 'G-BMN3MRDNS1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdyNhfj-brvb4bT4_DcRwjnaHNadcWNl4',
    appId: '1:43291649087:android:4e32245216ea99a246448a',
    messagingSenderId: '43291649087',
    projectId: 'smartcare-fyp',
    storageBucket: 'smartcare-fyp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDwodDlZW3rNzu_XNkk1UPKltvQyTU-tc',
    appId: '1:43291649087:ios:1af56b559946eb0546448a',
    messagingSenderId: '43291649087',
    projectId: 'smartcare-fyp',
    storageBucket: 'smartcare-fyp.firebasestorage.app',
    iosBundleId: 'com.example.smartcareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDwodDlZW3rNzu_XNkk1UPKltvQyTU-tc',
    appId: '1:43291649087:ios:1af56b559946eb0546448a',
    messagingSenderId: '43291649087',
    projectId: 'smartcare-fyp',
    storageBucket: 'smartcare-fyp.firebasestorage.app',
    iosBundleId: 'com.example.smartcareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClcguSXqfoAeBDM77DxUxMgBHDkAkOp0o',
    appId: '1:43291649087:web:6f5a1b8bb94fce0e46448a',
    messagingSenderId: '43291649087',
    projectId: 'smartcare-fyp',
    authDomain: 'smartcare-fyp.firebaseapp.com',
    storageBucket: 'smartcare-fyp.firebasestorage.app',
    measurementId: 'G-DDHWP8X65M',
  );

}